// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "gmem"
#define AUTOTB_TVIN_gmem  "../tv/cdatafile/c.filter_wrapper.autotvin_gmem.dat"
#define AUTOTB_TVOUT_gmem  "../tv/cdatafile/c.filter_wrapper.autotvout_gmem.dat"
// wrapc file define: "in_array"
#define AUTOTB_TVIN_in_array  "../tv/cdatafile/c.filter_wrapper.autotvin_in_array.dat"
// wrapc file define: "out_array"
#define AUTOTB_TVIN_out_array  "../tv/cdatafile/c.filter_wrapper.autotvin_out_array.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "gmem"
#define AUTOTB_TVOUT_PC_gmem  "../tv/rtldatafile/rtl.filter_wrapper.autotvout_gmem.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			gmem_depth = 0;
			in_array_depth = 0;
			out_array_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{gmem " << gmem_depth << "}\n";
			total_list << "{in_array " << in_array_depth << "}\n";
			total_list << "{out_array " << out_array_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int gmem_depth;
		int in_array_depth;
		int out_array_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void filter_wrapper (
int in_array[10000],
int out_array[9604]);

void AESL_WRAP_filter_wrapper (
int in_array[10000],
int out_array[9604])
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "gmem"
		aesl_fh.read(AUTOTB_TVOUT_PC_gmem, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_gmem, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_gmem, AESL_token); // data

			sc_bv<32> *gmem_pc_buffer = new sc_bv<32>[19604];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'gmem', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'gmem', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					gmem_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_gmem, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_gmem))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: gmem
				{
					// bitslice(31, 0)
					// {
						// celement: in_array(31, 0)
						// {
							sc_lv<32>* in_array_lv0_0_9999_1 = new sc_lv<32>[19604];
						// }
						// celement: out_array(31, 0)
						// {
							sc_lv<32>* out_array_lv0_0_9603_1 = new sc_lv<32>[19604];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: in_array(31, 0)
						{
							// carray: (0) => (9999) @ (1)
							for (int i_0 = 0; i_0 <= 9999; i_0 += 1)
							{
								hls_map_index++;
							}
						}
						// celement: out_array(31, 0)
						{
							// carray: (0) => (9603) @ (1)
							for (int i_0 = 0; i_0 <= 9603; i_0 += 1)
							{
								if (&(out_array[0]) != NULL) // check the null address if the c port is array or others
								{
									out_array_lv0_0_9603_1[hls_map_index].range(31, 0) = sc_bv<32>(gmem_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: in_array(31, 0)
						{
							// carray: (0) => (9999) @ (1)
							for (int i_0 = 0; i_0 <= 9999; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : in_array[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : in_array[0]
								// output_left_conversion : in_array[i_0]
								// output_type_conversion : (in_array_lv0_0_9999_1[hls_map_index]).to_uint64()
								hls_map_index++;
							}
						}
						// celement: out_array(31, 0)
						{
							// carray: (0) => (9603) @ (1)
							for (int i_0 = 0; i_0 <= 9603; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : out_array[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : out_array[0]
								// output_left_conversion : out_array[i_0]
								// output_type_conversion : (out_array_lv0_0_9603_1[hls_map_index]).to_uint64()
								if (&(out_array[0]) != NULL) // check the null address if the c port is array or others
								{
									out_array[i_0] = (out_array_lv0_0_9603_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] gmem_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "gmem"
		char* tvin_gmem = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_gmem);
		char* tvout_gmem = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_gmem);

		// "in_array"
		char* tvin_in_array = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_in_array);

		// "out_array"
		char* tvin_out_array = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_out_array);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_gmem, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_gmem, tvin_gmem);

		sc_bv<32>* gmem_tvin_wrapc_buffer = new sc_bv<32>[19604];

		// RTL Name: gmem
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: in_array(31, 0)
				{
					// carray: (0) => (9999) @ (1)
					for (int i_0 = 0; i_0 <= 9999; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : in_array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in_array[0]
						// regulate_c_name       : in_array
						// input_type_conversion : in_array[i_0]
						if (&(in_array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> in_array_tmp_mem;
							in_array_tmp_mem = in_array[i_0];
							gmem_tvin_wrapc_buffer[hls_map_index].range(31, 0) = in_array_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
				// celement: out_array(31, 0)
				{
					// carray: (0) => (9603) @ (1)
					for (int i_0 = 0; i_0 <= 9603; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : out_array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : out_array[0]
						// regulate_c_name       : out_array
						// input_type_conversion : out_array[i_0]
						if (&(out_array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> out_array_tmp_mem;
							out_array_tmp_mem = out_array[i_0];
							gmem_tvin_wrapc_buffer[hls_map_index].range(31, 0) = out_array_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 19604; i++)
		{
			sprintf(tvin_gmem, "%s\n", (gmem_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_gmem, tvin_gmem);
		}

		tcl_file.set_num(19604, &tcl_file.gmem_depth);
		sprintf(tvin_gmem, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_gmem, tvin_gmem);

		// release memory allocation
		delete [] gmem_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_in_array, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_in_array, tvin_in_array);

		sc_bv<32> in_array_tvin_wrapc_buffer;

		// RTL Name: in_array
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_in_array, "%s\n", (in_array_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_in_array, tvin_in_array);
		}

		tcl_file.set_num(1, &tcl_file.in_array_depth);
		sprintf(tvin_in_array, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_in_array, tvin_in_array);

		// [[transaction]]
		sprintf(tvin_out_array, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_out_array, tvin_out_array);

		sc_bv<32> out_array_tvin_wrapc_buffer;

		// RTL Name: out_array
		{
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_out_array, "%s\n", (out_array_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_out_array, tvin_out_array);
		}

		tcl_file.set_num(1, &tcl_file.out_array_depth);
		sprintf(tvin_out_array, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_out_array, tvin_out_array);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		filter_wrapper(in_array, out_array);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_gmem, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_gmem, tvout_gmem);

		sc_bv<32>* gmem_tvout_wrapc_buffer = new sc_bv<32>[19604];

		// RTL Name: gmem
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: in_array(31, 0)
				{
					// carray: (0) => (9999) @ (1)
					for (int i_0 = 0; i_0 <= 9999; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : in_array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : in_array[0]
						// regulate_c_name       : in_array
						// input_type_conversion : in_array[i_0]
						if (&(in_array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> in_array_tmp_mem;
							in_array_tmp_mem = in_array[i_0];
							gmem_tvout_wrapc_buffer[hls_map_index].range(31, 0) = in_array_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
				// celement: out_array(31, 0)
				{
					// carray: (0) => (9603) @ (1)
					for (int i_0 = 0; i_0 <= 9603; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : out_array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : out_array[0]
						// regulate_c_name       : out_array
						// input_type_conversion : out_array[i_0]
						if (&(out_array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> out_array_tmp_mem;
							out_array_tmp_mem = out_array[i_0];
							gmem_tvout_wrapc_buffer[hls_map_index].range(31, 0) = out_array_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 19604; i++)
		{
			sprintf(tvout_gmem, "%s\n", (gmem_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_gmem, tvout_gmem);
		}

		tcl_file.set_num(19604, &tcl_file.gmem_depth);
		sprintf(tvout_gmem, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_gmem, tvout_gmem);

		// release memory allocation
		delete [] gmem_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "gmem"
		delete [] tvin_gmem;
		delete [] tvout_gmem;
		// release memory allocation: "in_array"
		delete [] tvin_in_array;
		// release memory allocation: "out_array"
		delete [] tvin_out_array;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

