lappend pragmaStatus0 {pragma "STREAM" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "conv_stream" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'conv_stream' does not exist in any synthesis source file." variable "out_stream"}
lappend pragmaStatus1 {pragma "STREAM" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "conv_stream" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'conv_stream' does not exist in any synthesis source file." variable "in_stream"}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "write_pixels_to_stream/write_pixels_to_stream_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "read_pixels_from_stream/read_pixels_from_stream_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "PIPELINE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "bubble_sort/bubble_sort_inner_loop" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "UNROLL" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "bubble_sort/bubble_sort_outer_loop" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'bubble_sort_outer_loop' does not exist in function 'bubble_sort'. "}
lappend pragmaStatus6 {pragma "PIPELINE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "bubble_sort/bubble_sort_mapping" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter/conv_cols" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'conv_cols' does not exist in function 'filter'. "}
lappend pragmaStatus8 {pragma "STREAM" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter_wrapper" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "in_stream"}
lappend pragmaStatus9 {pragma "STREAM" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter_wrapper" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "out_stream"}
lappend pragmaStatus10 {pragma "PIPELINE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter/filter_cols" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "INTERFACE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter_wrapper" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "INTERFACE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter_wrapper" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "INTERFACE" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter_wrapper" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "DATAFLOW" source "/home/kinka1/HLS/MedianFilter/median.cpp" location "filter_wrapper" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
