// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "read_pixels_from_str.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic read_pixels_from_str::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic read_pixels_from_str::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_state1 = "1";
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_state2 = "10";
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_state6 = "1000";
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_state7 = "10000";
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_state8 = "100000";
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_state9 = "1000000";
const sc_lv<8> read_pixels_from_str::ap_ST_fsm_state10 = "10000000";
const sc_lv<32> read_pixels_from_str::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool read_pixels_from_str::ap_const_boolean_1 = true;
const sc_lv<1> read_pixels_from_str::ap_const_lv1_0 = "0";
const sc_lv<3> read_pixels_from_str::ap_const_lv3_0 = "000";
const sc_lv<2> read_pixels_from_str::ap_const_lv2_0 = "00";
const sc_lv<4> read_pixels_from_str::ap_const_lv4_0 = "0000";
const sc_lv<32> read_pixels_from_str::ap_const_lv32_2 = "10";
const bool read_pixels_from_str::ap_const_boolean_0 = false;
const sc_lv<32> read_pixels_from_str::ap_const_lv32_1 = "1";
const sc_lv<32> read_pixels_from_str::ap_const_lv32_7 = "111";
const sc_lv<1> read_pixels_from_str::ap_const_lv1_1 = "1";
const sc_lv<19> read_pixels_from_str::ap_const_lv19_0 = "0000000000000000000";
const sc_lv<32> read_pixels_from_str::ap_const_lv32_574E4 = "1010111010011100100";
const sc_lv<4> read_pixels_from_str::ap_const_lv4_F = "1111";
const sc_lv<32> read_pixels_from_str::ap_const_lv32_1F = "11111";
const sc_lv<19> read_pixels_from_str::ap_const_lv19_574E4 = "1010111010011100100";
const sc_lv<19> read_pixels_from_str::ap_const_lv19_1 = "1";

read_pixels_from_str::read_pixels_from_str(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( out_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_174 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( out_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_174 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( out_stream_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_174 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( out_array_offset_empty_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( out_stream_V_empty_n );
    sensitive << ( exitcond_i_reg_174 );

    SC_METHOD(thread_ap_block_state5_io);
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_reg_174 );
    sensitive << ( ap_sig_ioackin_m_axi_out_array_WREADY );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond_i_fu_151_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( m_axi_out_array_BVALID );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( m_axi_out_array_BVALID );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_out_array_AWREADY);
    sensitive << ( m_axi_out_array_AWREADY );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_AWREADY );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_out_array_WREADY);
    sensitive << ( m_axi_out_array_WREADY );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_WREADY );

    SC_METHOD(thread_exitcond_i_fu_151_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_i_reg_120 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_i_fu_157_p2);
    sensitive << ( i_i_reg_120 );

    SC_METHOD(thread_m_axi_out_array_ARADDR);

    SC_METHOD(thread_m_axi_out_array_ARBURST);

    SC_METHOD(thread_m_axi_out_array_ARCACHE);

    SC_METHOD(thread_m_axi_out_array_ARID);

    SC_METHOD(thread_m_axi_out_array_ARLEN);

    SC_METHOD(thread_m_axi_out_array_ARLOCK);

    SC_METHOD(thread_m_axi_out_array_ARPROT);

    SC_METHOD(thread_m_axi_out_array_ARQOS);

    SC_METHOD(thread_m_axi_out_array_ARREGION);

    SC_METHOD(thread_m_axi_out_array_ARSIZE);

    SC_METHOD(thread_m_axi_out_array_ARUSER);

    SC_METHOD(thread_m_axi_out_array_ARVALID);

    SC_METHOD(thread_m_axi_out_array_AWADDR);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sext_i_fu_141_p1 );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_AWREADY );

    SC_METHOD(thread_m_axi_out_array_AWBURST);

    SC_METHOD(thread_m_axi_out_array_AWCACHE);

    SC_METHOD(thread_m_axi_out_array_AWID);

    SC_METHOD(thread_m_axi_out_array_AWLEN);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_AWREADY );

    SC_METHOD(thread_m_axi_out_array_AWLOCK);

    SC_METHOD(thread_m_axi_out_array_AWPROT);

    SC_METHOD(thread_m_axi_out_array_AWQOS);

    SC_METHOD(thread_m_axi_out_array_AWREGION);

    SC_METHOD(thread_m_axi_out_array_AWSIZE);

    SC_METHOD(thread_m_axi_out_array_AWUSER);

    SC_METHOD(thread_m_axi_out_array_AWVALID);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_AWREADY );

    SC_METHOD(thread_m_axi_out_array_BREADY);
    sensitive << ( m_axi_out_array_BVALID );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_m_axi_out_array_RREADY);

    SC_METHOD(thread_m_axi_out_array_WDATA);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_reg_174 );
    sensitive << ( tmp_reg_183 );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_WREADY );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_m_axi_out_array_WID);

    SC_METHOD(thread_m_axi_out_array_WLAST);

    SC_METHOD(thread_m_axi_out_array_WSTRB);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_reg_174 );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_WREADY );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_m_axi_out_array_WUSER);

    SC_METHOD(thread_m_axi_out_array_WVALID);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_reg_174 );
    sensitive << ( ap_reg_ioackin_m_axi_out_array_WREADY );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_out_array_blk_n_AW);
    sensitive << ( m_axi_out_array_AWREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_out_array_blk_n_B);
    sensitive << ( m_axi_out_array_BVALID );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_out_array_blk_n_W);
    sensitive << ( m_axi_out_array_WREADY );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_reg_174 );

    SC_METHOD(thread_out_array_offset_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_array_offset_empty_n );

    SC_METHOD(thread_out_array_offset_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_array_offset_empty_n );

    SC_METHOD(thread_out_stream_V_blk_n);
    sensitive << ( out_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_reg_174 );

    SC_METHOD(thread_out_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_i_reg_174 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_sext_i_fu_141_p1);
    sensitive << ( out_array_offset1_i_reg_163 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_out_array_BVALID );
    sensitive << ( out_array_offset_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_sig_ioackin_m_axi_out_array_AWREADY );
    sensitive << ( exitcond_i_fu_151_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_out_array_AWREADY = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_out_array_WREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "read_pixels_from_str_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_stream_V_dout, "(port)out_stream_V_dout");
    sc_trace(mVcdFile, out_stream_V_empty_n, "(port)out_stream_V_empty_n");
    sc_trace(mVcdFile, out_stream_V_read, "(port)out_stream_V_read");
    sc_trace(mVcdFile, m_axi_out_array_AWVALID, "(port)m_axi_out_array_AWVALID");
    sc_trace(mVcdFile, m_axi_out_array_AWREADY, "(port)m_axi_out_array_AWREADY");
    sc_trace(mVcdFile, m_axi_out_array_AWADDR, "(port)m_axi_out_array_AWADDR");
    sc_trace(mVcdFile, m_axi_out_array_AWID, "(port)m_axi_out_array_AWID");
    sc_trace(mVcdFile, m_axi_out_array_AWLEN, "(port)m_axi_out_array_AWLEN");
    sc_trace(mVcdFile, m_axi_out_array_AWSIZE, "(port)m_axi_out_array_AWSIZE");
    sc_trace(mVcdFile, m_axi_out_array_AWBURST, "(port)m_axi_out_array_AWBURST");
    sc_trace(mVcdFile, m_axi_out_array_AWLOCK, "(port)m_axi_out_array_AWLOCK");
    sc_trace(mVcdFile, m_axi_out_array_AWCACHE, "(port)m_axi_out_array_AWCACHE");
    sc_trace(mVcdFile, m_axi_out_array_AWPROT, "(port)m_axi_out_array_AWPROT");
    sc_trace(mVcdFile, m_axi_out_array_AWQOS, "(port)m_axi_out_array_AWQOS");
    sc_trace(mVcdFile, m_axi_out_array_AWREGION, "(port)m_axi_out_array_AWREGION");
    sc_trace(mVcdFile, m_axi_out_array_AWUSER, "(port)m_axi_out_array_AWUSER");
    sc_trace(mVcdFile, m_axi_out_array_WVALID, "(port)m_axi_out_array_WVALID");
    sc_trace(mVcdFile, m_axi_out_array_WREADY, "(port)m_axi_out_array_WREADY");
    sc_trace(mVcdFile, m_axi_out_array_WDATA, "(port)m_axi_out_array_WDATA");
    sc_trace(mVcdFile, m_axi_out_array_WSTRB, "(port)m_axi_out_array_WSTRB");
    sc_trace(mVcdFile, m_axi_out_array_WLAST, "(port)m_axi_out_array_WLAST");
    sc_trace(mVcdFile, m_axi_out_array_WID, "(port)m_axi_out_array_WID");
    sc_trace(mVcdFile, m_axi_out_array_WUSER, "(port)m_axi_out_array_WUSER");
    sc_trace(mVcdFile, m_axi_out_array_ARVALID, "(port)m_axi_out_array_ARVALID");
    sc_trace(mVcdFile, m_axi_out_array_ARREADY, "(port)m_axi_out_array_ARREADY");
    sc_trace(mVcdFile, m_axi_out_array_ARADDR, "(port)m_axi_out_array_ARADDR");
    sc_trace(mVcdFile, m_axi_out_array_ARID, "(port)m_axi_out_array_ARID");
    sc_trace(mVcdFile, m_axi_out_array_ARLEN, "(port)m_axi_out_array_ARLEN");
    sc_trace(mVcdFile, m_axi_out_array_ARSIZE, "(port)m_axi_out_array_ARSIZE");
    sc_trace(mVcdFile, m_axi_out_array_ARBURST, "(port)m_axi_out_array_ARBURST");
    sc_trace(mVcdFile, m_axi_out_array_ARLOCK, "(port)m_axi_out_array_ARLOCK");
    sc_trace(mVcdFile, m_axi_out_array_ARCACHE, "(port)m_axi_out_array_ARCACHE");
    sc_trace(mVcdFile, m_axi_out_array_ARPROT, "(port)m_axi_out_array_ARPROT");
    sc_trace(mVcdFile, m_axi_out_array_ARQOS, "(port)m_axi_out_array_ARQOS");
    sc_trace(mVcdFile, m_axi_out_array_ARREGION, "(port)m_axi_out_array_ARREGION");
    sc_trace(mVcdFile, m_axi_out_array_ARUSER, "(port)m_axi_out_array_ARUSER");
    sc_trace(mVcdFile, m_axi_out_array_RVALID, "(port)m_axi_out_array_RVALID");
    sc_trace(mVcdFile, m_axi_out_array_RREADY, "(port)m_axi_out_array_RREADY");
    sc_trace(mVcdFile, m_axi_out_array_RDATA, "(port)m_axi_out_array_RDATA");
    sc_trace(mVcdFile, m_axi_out_array_RLAST, "(port)m_axi_out_array_RLAST");
    sc_trace(mVcdFile, m_axi_out_array_RID, "(port)m_axi_out_array_RID");
    sc_trace(mVcdFile, m_axi_out_array_RUSER, "(port)m_axi_out_array_RUSER");
    sc_trace(mVcdFile, m_axi_out_array_RRESP, "(port)m_axi_out_array_RRESP");
    sc_trace(mVcdFile, m_axi_out_array_BVALID, "(port)m_axi_out_array_BVALID");
    sc_trace(mVcdFile, m_axi_out_array_BREADY, "(port)m_axi_out_array_BREADY");
    sc_trace(mVcdFile, m_axi_out_array_BRESP, "(port)m_axi_out_array_BRESP");
    sc_trace(mVcdFile, m_axi_out_array_BID, "(port)m_axi_out_array_BID");
    sc_trace(mVcdFile, m_axi_out_array_BUSER, "(port)m_axi_out_array_BUSER");
    sc_trace(mVcdFile, out_array_offset_dout, "(port)out_array_offset_dout");
    sc_trace(mVcdFile, out_array_offset_empty_n, "(port)out_array_offset_empty_n");
    sc_trace(mVcdFile, out_array_offset_read, "(port)out_array_offset_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_stream_V_blk_n, "out_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_i_reg_174, "exitcond_i_reg_174");
    sc_trace(mVcdFile, out_array_blk_n_AW, "out_array_blk_n_AW");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, out_array_blk_n_W, "out_array_blk_n_W");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_exitcond_i_reg_174, "ap_reg_pp0_iter1_exitcond_i_reg_174");
    sc_trace(mVcdFile, out_array_blk_n_B, "out_array_blk_n_B");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, out_array_offset_blk_n, "out_array_offset_blk_n");
    sc_trace(mVcdFile, i_i_reg_120, "i_i_reg_120");
    sc_trace(mVcdFile, out_array_offset1_i_reg_163, "out_array_offset1_i_reg_163");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_out_array_AWREADY, "ap_sig_ioackin_m_axi_out_array_AWREADY");
    sc_trace(mVcdFile, exitcond_i_fu_151_p2, "exitcond_i_fu_151_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_out_array_WREADY, "ap_sig_ioackin_m_axi_out_array_WREADY");
    sc_trace(mVcdFile, ap_block_state5_io, "ap_block_state5_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_157_p2, "i_fu_157_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_reg_183, "tmp_reg_183");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, sext_i_fu_141_p1, "sext_i_fu_141_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_out_array_AWREADY, "ap_reg_ioackin_m_axi_out_array_AWREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_out_array_WREADY, "ap_reg_ioackin_m_axi_out_array_WREADY");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

read_pixels_from_str::~read_pixels_from_str() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void read_pixels_from_str::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                    esl_seteq<1,1,1>(m_axi_out_array_BVALID.read(), ap_const_logic_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_out_array_AWREADY.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_out_array_AWREADY.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_out_array_AWREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_out_array_AWREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_m_axi_out_array_AWREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_out_array_AWREADY.read())) {
                ap_reg_ioackin_m_axi_out_array_AWREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_out_array_WREADY = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_reg_174.read()))) {
            if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
                ap_reg_ioackin_m_axi_out_array_WREADY = ap_const_logic_0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, m_axi_out_array_WREADY.read()) && 
                        esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0))) {
                ap_reg_ioackin_m_axi_out_array_WREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_151_p2.read()))) {
        i_i_reg_120 = i_fu_157_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_out_array_AWREADY.read(), ap_const_logic_1))) {
        i_i_reg_120 = ap_const_lv19_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_exitcond_i_reg_174 = exitcond_i_reg_174.read();
        exitcond_i_reg_174 = exitcond_i_fu_151_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, out_array_offset_empty_n.read())))) {
        out_array_offset1_i_reg_163 = out_array_offset_dout.read().range(31, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_174.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_reg_183 = out_stream_V_dout.read();
    }
}

void read_pixels_from_str::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void read_pixels_from_str::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void read_pixels_from_str::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[7];
}

void read_pixels_from_str::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void read_pixels_from_str::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void read_pixels_from_str::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_174.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_empty_n.read()));
}

void read_pixels_from_str::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_174.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read())));
}

void read_pixels_from_str::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_174.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read())));
}

void read_pixels_from_str::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, out_array_offset_empty_n.read()));
}

void read_pixels_from_str::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void read_pixels_from_str::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_174.read()) && esl_seteq<1,1,1>(ap_const_logic_0, out_stream_V_empty_n.read()));
}

void read_pixels_from_str::thread_ap_block_state5_io() {
    ap_block_state5_io = (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_reg_174.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_out_array_WREADY.read()));
}

void read_pixels_from_str::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void read_pixels_from_str::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(exitcond_i_fu_151_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(m_axi_out_array_BVALID.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void read_pixels_from_str::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void read_pixels_from_str::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(m_axi_out_array_BVALID.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_ap_sig_ioackin_m_axi_out_array_AWREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_out_array_AWREADY.read())) {
        ap_sig_ioackin_m_axi_out_array_AWREADY = m_axi_out_array_AWREADY.read();
    } else {
        ap_sig_ioackin_m_axi_out_array_AWREADY = ap_const_logic_1;
    }
}

void read_pixels_from_str::thread_ap_sig_ioackin_m_axi_out_array_WREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_out_array_WREADY.read())) {
        ap_sig_ioackin_m_axi_out_array_WREADY = m_axi_out_array_WREADY.read();
    } else {
        ap_sig_ioackin_m_axi_out_array_WREADY = ap_const_logic_1;
    }
}

void read_pixels_from_str::thread_exitcond_i_fu_151_p2() {
    exitcond_i_fu_151_p2 = (!i_i_reg_120.read().is_01() || !ap_const_lv19_574E4.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_120.read() == ap_const_lv19_574E4);
}

void read_pixels_from_str::thread_i_fu_157_p2() {
    i_fu_157_p2 = (!i_i_reg_120.read().is_01() || !ap_const_lv19_1.is_01())? sc_lv<19>(): (sc_biguint<19>(i_i_reg_120.read()) + sc_biguint<19>(ap_const_lv19_1));
}

void read_pixels_from_str::thread_m_axi_out_array_ARADDR() {
    m_axi_out_array_ARADDR = ap_const_lv32_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARBURST() {
    m_axi_out_array_ARBURST = ap_const_lv2_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARCACHE() {
    m_axi_out_array_ARCACHE = ap_const_lv4_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARID() {
    m_axi_out_array_ARID = ap_const_lv1_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARLEN() {
    m_axi_out_array_ARLEN = ap_const_lv32_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARLOCK() {
    m_axi_out_array_ARLOCK = ap_const_lv2_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARPROT() {
    m_axi_out_array_ARPROT = ap_const_lv3_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARQOS() {
    m_axi_out_array_ARQOS = ap_const_lv4_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARREGION() {
    m_axi_out_array_ARREGION = ap_const_lv4_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARSIZE() {
    m_axi_out_array_ARSIZE = ap_const_lv3_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARUSER() {
    m_axi_out_array_ARUSER = ap_const_lv1_0;
}

void read_pixels_from_str::thread_m_axi_out_array_ARVALID() {
    m_axi_out_array_ARVALID = ap_const_logic_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWADDR() {
    m_axi_out_array_AWADDR =  (sc_lv<32>) (sext_i_fu_141_p1.read());
}

void read_pixels_from_str::thread_m_axi_out_array_AWBURST() {
    m_axi_out_array_AWBURST = ap_const_lv2_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWCACHE() {
    m_axi_out_array_AWCACHE = ap_const_lv4_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWID() {
    m_axi_out_array_AWID = ap_const_lv1_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWLEN() {
    m_axi_out_array_AWLEN = ap_const_lv32_574E4;
}

void read_pixels_from_str::thread_m_axi_out_array_AWLOCK() {
    m_axi_out_array_AWLOCK = ap_const_lv2_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWPROT() {
    m_axi_out_array_AWPROT = ap_const_lv3_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWQOS() {
    m_axi_out_array_AWQOS = ap_const_lv4_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWREGION() {
    m_axi_out_array_AWREGION = ap_const_lv4_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWSIZE() {
    m_axi_out_array_AWSIZE = ap_const_lv3_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWUSER() {
    m_axi_out_array_AWUSER = ap_const_lv1_0;
}

void read_pixels_from_str::thread_m_axi_out_array_AWVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_out_array_AWREADY.read()))) {
        m_axi_out_array_AWVALID = ap_const_logic_1;
    } else {
        m_axi_out_array_AWVALID = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_m_axi_out_array_BREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(m_axi_out_array_BVALID.read(), ap_const_logic_1))) {
        m_axi_out_array_BREADY = ap_const_logic_1;
    } else {
        m_axi_out_array_BREADY = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_m_axi_out_array_RREADY() {
    m_axi_out_array_RREADY = ap_const_logic_0;
}

void read_pixels_from_str::thread_m_axi_out_array_WDATA() {
    m_axi_out_array_WDATA = tmp_reg_183.read();
}

void read_pixels_from_str::thread_m_axi_out_array_WID() {
    m_axi_out_array_WID = ap_const_lv1_0;
}

void read_pixels_from_str::thread_m_axi_out_array_WLAST() {
    m_axi_out_array_WLAST = ap_const_logic_0;
}

void read_pixels_from_str::thread_m_axi_out_array_WSTRB() {
    m_axi_out_array_WSTRB = ap_const_lv4_F;
}

void read_pixels_from_str::thread_m_axi_out_array_WUSER() {
    m_axi_out_array_WUSER = ap_const_lv1_0;
}

void read_pixels_from_str::thread_m_axi_out_array_WVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_reg_174.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_out_array_WREADY.read()))) {
        m_axi_out_array_WVALID = ap_const_logic_1;
    } else {
        m_axi_out_array_WVALID = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_out_array_blk_n_AW() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        out_array_blk_n_AW = m_axi_out_array_AWREADY.read();
    } else {
        out_array_blk_n_AW = ap_const_logic_1;
    }
}

void read_pixels_from_str::thread_out_array_blk_n_B() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        out_array_blk_n_B = m_axi_out_array_BVALID.read();
    } else {
        out_array_blk_n_B = ap_const_logic_1;
    }
}

void read_pixels_from_str::thread_out_array_blk_n_W() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_reg_174.read()))) {
        out_array_blk_n_W = m_axi_out_array_WREADY.read();
    } else {
        out_array_blk_n_W = ap_const_logic_1;
    }
}

void read_pixels_from_str::thread_out_array_offset_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        out_array_offset_blk_n = out_array_offset_empty_n.read();
    } else {
        out_array_offset_blk_n = ap_const_logic_1;
    }
}

void read_pixels_from_str::thread_out_array_offset_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, out_array_offset_empty_n.read())))) {
        out_array_offset_read = ap_const_logic_1;
    } else {
        out_array_offset_read = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_out_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_174.read()))) {
        out_stream_V_blk_n = out_stream_V_empty_n.read();
    } else {
        out_stream_V_blk_n = ap_const_logic_1;
    }
}

void read_pixels_from_str::thread_out_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_reg_174.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_stream_V_read = ap_const_logic_1;
    } else {
        out_stream_V_read = ap_const_logic_0;
    }
}

void read_pixels_from_str::thread_sext_i_fu_141_p1() {
    sext_i_fu_141_p1 = esl_zext<64,30>(out_array_offset1_i_reg_163.read());
}

void read_pixels_from_str::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, out_array_offset_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_out_array_AWREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_i_fu_151_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(exitcond_i_fu_151_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(m_axi_out_array_BVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

