// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "write_pixels_to_stre.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic write_pixels_to_stre::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic write_pixels_to_stre::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state1 = "1";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state2 = "10";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state3 = "100";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state4 = "1000";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state5 = "10000";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state6 = "100000";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_pp0_stage0 = "10000000";
const sc_lv<9> write_pixels_to_stre::ap_ST_fsm_state11 = "100000000";
const bool write_pixels_to_stre::ap_const_boolean_1 = true;
const sc_lv<32> write_pixels_to_stre::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> write_pixels_to_stre::ap_const_lv1_0 = "0";
const sc_lv<3> write_pixels_to_stre::ap_const_lv3_0 = "000";
const sc_lv<2> write_pixels_to_stre::ap_const_lv2_0 = "00";
const sc_lv<4> write_pixels_to_stre::ap_const_lv4_0 = "0000";
const bool write_pixels_to_stre::ap_const_boolean_0 = false;
const sc_lv<32> write_pixels_to_stre::ap_const_lv32_7 = "111";
const sc_lv<32> write_pixels_to_stre::ap_const_lv32_6 = "110";
const sc_lv<1> write_pixels_to_stre::ap_const_lv1_1 = "1";
const sc_lv<19> write_pixels_to_stre::ap_const_lv19_0 = "0000000000000000000";
const sc_lv<32> write_pixels_to_stre::ap_const_lv32_57E40 = "1010111111001000000";
const sc_lv<32> write_pixels_to_stre::ap_const_lv32_2 = "10";
const sc_lv<32> write_pixels_to_stre::ap_const_lv32_1F = "11111";
const sc_lv<19> write_pixels_to_stre::ap_const_lv19_57E40 = "1010111111001000000";
const sc_lv<19> write_pixels_to_stre::ap_const_lv19_1 = "1";
const sc_lv<32> write_pixels_to_stre::ap_const_lv32_8 = "1000";

write_pixels_to_stre::write_pixels_to_stre(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( in_stream_V_full_n );
    sensitive << ( m_axi_in_array_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_i_i_reg_183 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_i_reg_183 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_stream_V_full_n );
    sensitive << ( m_axi_in_array_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_i_i_reg_183 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_i_reg_183 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_stream_V_full_n );
    sensitive << ( m_axi_in_array_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_i_i_reg_183 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_i_reg_183 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter2);
    sensitive << ( in_stream_V_full_n );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_i_reg_183 );

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter1);
    sensitive << ( m_axi_in_array_RVALID );
    sensitive << ( exitcond_i_i_reg_183 );

    SC_METHOD(thread_ap_condition_153);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_ioackin_m_axi_in_array_ARREADY );

    SC_METHOD(thread_ap_condition_298);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( m_axi_in_array_ARREADY );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state8);
    sensitive << ( exitcond_i_i_fu_165_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_in_array_ARREADY);
    sensitive << ( m_axi_in_array_ARREADY );
    sensitive << ( ap_reg_ioackin_m_axi_in_array_ARREADY );

    SC_METHOD(thread_exitcond_i_i_fu_165_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_i_i_reg_133 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_i_fu_171_p2);
    sensitive << ( i_i_i_reg_133 );

    SC_METHOD(thread_in_array_blk_n_AR);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_in_array_ARREADY );

    SC_METHOD(thread_in_array_blk_n_R);
    sensitive << ( m_axi_in_array_RVALID );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_i_i_reg_183 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_in_array_offset1_i_i_fu_144_p4);
    sensitive << ( in_array_offset );

    SC_METHOD(thread_in_stream_V_blk_n);
    sensitive << ( in_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_i_reg_183 );

    SC_METHOD(thread_in_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_i_reg_183 );
    sensitive << ( temp_reg_192 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_in_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_reg_pp0_iter1_exitcond_i_i_reg_183 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_m_axi_in_array_ARADDR);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sext_i_i_fu_154_p1 );
    sensitive << ( ap_reg_ioackin_m_axi_in_array_ARREADY );

    SC_METHOD(thread_m_axi_in_array_ARBURST);

    SC_METHOD(thread_m_axi_in_array_ARCACHE);

    SC_METHOD(thread_m_axi_in_array_ARID);

    SC_METHOD(thread_m_axi_in_array_ARLEN);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_reg_ioackin_m_axi_in_array_ARREADY );

    SC_METHOD(thread_m_axi_in_array_ARLOCK);

    SC_METHOD(thread_m_axi_in_array_ARPROT);

    SC_METHOD(thread_m_axi_in_array_ARQOS);

    SC_METHOD(thread_m_axi_in_array_ARREGION);

    SC_METHOD(thread_m_axi_in_array_ARSIZE);

    SC_METHOD(thread_m_axi_in_array_ARUSER);

    SC_METHOD(thread_m_axi_in_array_ARVALID);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_reg_ioackin_m_axi_in_array_ARREADY );

    SC_METHOD(thread_m_axi_in_array_AWADDR);

    SC_METHOD(thread_m_axi_in_array_AWBURST);

    SC_METHOD(thread_m_axi_in_array_AWCACHE);

    SC_METHOD(thread_m_axi_in_array_AWID);

    SC_METHOD(thread_m_axi_in_array_AWLEN);

    SC_METHOD(thread_m_axi_in_array_AWLOCK);

    SC_METHOD(thread_m_axi_in_array_AWPROT);

    SC_METHOD(thread_m_axi_in_array_AWQOS);

    SC_METHOD(thread_m_axi_in_array_AWREGION);

    SC_METHOD(thread_m_axi_in_array_AWSIZE);

    SC_METHOD(thread_m_axi_in_array_AWUSER);

    SC_METHOD(thread_m_axi_in_array_AWVALID);

    SC_METHOD(thread_m_axi_in_array_BREADY);

    SC_METHOD(thread_m_axi_in_array_RREADY);
    sensitive << ( exitcond_i_i_reg_183 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_m_axi_in_array_WDATA);

    SC_METHOD(thread_m_axi_in_array_WID);

    SC_METHOD(thread_m_axi_in_array_WLAST);

    SC_METHOD(thread_m_axi_in_array_WSTRB);

    SC_METHOD(thread_m_axi_in_array_WUSER);

    SC_METHOD(thread_m_axi_in_array_WVALID);

    SC_METHOD(thread_out_array_out_blk_n);
    sensitive << ( out_array_out_full_n );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_array_out_din);
    sensitive << ( out_array );
    sensitive << ( out_array_out_full_n );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_array_out_write);
    sensitive << ( out_array_out_full_n );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_sext_i_i_fu_154_p1);
    sensitive << ( in_array_offset1_i_i_fu_144_p4 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_array_out_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_sig_ioackin_m_axi_in_array_ARREADY );
    sensitive << ( exitcond_i_i_fu_165_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_in_array_ARREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "write_pixels_to_stre_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, in_stream_V_din, "(port)in_stream_V_din");
    sc_trace(mVcdFile, in_stream_V_full_n, "(port)in_stream_V_full_n");
    sc_trace(mVcdFile, in_stream_V_write, "(port)in_stream_V_write");
    sc_trace(mVcdFile, m_axi_in_array_AWVALID, "(port)m_axi_in_array_AWVALID");
    sc_trace(mVcdFile, m_axi_in_array_AWREADY, "(port)m_axi_in_array_AWREADY");
    sc_trace(mVcdFile, m_axi_in_array_AWADDR, "(port)m_axi_in_array_AWADDR");
    sc_trace(mVcdFile, m_axi_in_array_AWID, "(port)m_axi_in_array_AWID");
    sc_trace(mVcdFile, m_axi_in_array_AWLEN, "(port)m_axi_in_array_AWLEN");
    sc_trace(mVcdFile, m_axi_in_array_AWSIZE, "(port)m_axi_in_array_AWSIZE");
    sc_trace(mVcdFile, m_axi_in_array_AWBURST, "(port)m_axi_in_array_AWBURST");
    sc_trace(mVcdFile, m_axi_in_array_AWLOCK, "(port)m_axi_in_array_AWLOCK");
    sc_trace(mVcdFile, m_axi_in_array_AWCACHE, "(port)m_axi_in_array_AWCACHE");
    sc_trace(mVcdFile, m_axi_in_array_AWPROT, "(port)m_axi_in_array_AWPROT");
    sc_trace(mVcdFile, m_axi_in_array_AWQOS, "(port)m_axi_in_array_AWQOS");
    sc_trace(mVcdFile, m_axi_in_array_AWREGION, "(port)m_axi_in_array_AWREGION");
    sc_trace(mVcdFile, m_axi_in_array_AWUSER, "(port)m_axi_in_array_AWUSER");
    sc_trace(mVcdFile, m_axi_in_array_WVALID, "(port)m_axi_in_array_WVALID");
    sc_trace(mVcdFile, m_axi_in_array_WREADY, "(port)m_axi_in_array_WREADY");
    sc_trace(mVcdFile, m_axi_in_array_WDATA, "(port)m_axi_in_array_WDATA");
    sc_trace(mVcdFile, m_axi_in_array_WSTRB, "(port)m_axi_in_array_WSTRB");
    sc_trace(mVcdFile, m_axi_in_array_WLAST, "(port)m_axi_in_array_WLAST");
    sc_trace(mVcdFile, m_axi_in_array_WID, "(port)m_axi_in_array_WID");
    sc_trace(mVcdFile, m_axi_in_array_WUSER, "(port)m_axi_in_array_WUSER");
    sc_trace(mVcdFile, m_axi_in_array_ARVALID, "(port)m_axi_in_array_ARVALID");
    sc_trace(mVcdFile, m_axi_in_array_ARREADY, "(port)m_axi_in_array_ARREADY");
    sc_trace(mVcdFile, m_axi_in_array_ARADDR, "(port)m_axi_in_array_ARADDR");
    sc_trace(mVcdFile, m_axi_in_array_ARID, "(port)m_axi_in_array_ARID");
    sc_trace(mVcdFile, m_axi_in_array_ARLEN, "(port)m_axi_in_array_ARLEN");
    sc_trace(mVcdFile, m_axi_in_array_ARSIZE, "(port)m_axi_in_array_ARSIZE");
    sc_trace(mVcdFile, m_axi_in_array_ARBURST, "(port)m_axi_in_array_ARBURST");
    sc_trace(mVcdFile, m_axi_in_array_ARLOCK, "(port)m_axi_in_array_ARLOCK");
    sc_trace(mVcdFile, m_axi_in_array_ARCACHE, "(port)m_axi_in_array_ARCACHE");
    sc_trace(mVcdFile, m_axi_in_array_ARPROT, "(port)m_axi_in_array_ARPROT");
    sc_trace(mVcdFile, m_axi_in_array_ARQOS, "(port)m_axi_in_array_ARQOS");
    sc_trace(mVcdFile, m_axi_in_array_ARREGION, "(port)m_axi_in_array_ARREGION");
    sc_trace(mVcdFile, m_axi_in_array_ARUSER, "(port)m_axi_in_array_ARUSER");
    sc_trace(mVcdFile, m_axi_in_array_RVALID, "(port)m_axi_in_array_RVALID");
    sc_trace(mVcdFile, m_axi_in_array_RREADY, "(port)m_axi_in_array_RREADY");
    sc_trace(mVcdFile, m_axi_in_array_RDATA, "(port)m_axi_in_array_RDATA");
    sc_trace(mVcdFile, m_axi_in_array_RLAST, "(port)m_axi_in_array_RLAST");
    sc_trace(mVcdFile, m_axi_in_array_RID, "(port)m_axi_in_array_RID");
    sc_trace(mVcdFile, m_axi_in_array_RUSER, "(port)m_axi_in_array_RUSER");
    sc_trace(mVcdFile, m_axi_in_array_RRESP, "(port)m_axi_in_array_RRESP");
    sc_trace(mVcdFile, m_axi_in_array_BVALID, "(port)m_axi_in_array_BVALID");
    sc_trace(mVcdFile, m_axi_in_array_BREADY, "(port)m_axi_in_array_BREADY");
    sc_trace(mVcdFile, m_axi_in_array_BRESP, "(port)m_axi_in_array_BRESP");
    sc_trace(mVcdFile, m_axi_in_array_BID, "(port)m_axi_in_array_BID");
    sc_trace(mVcdFile, m_axi_in_array_BUSER, "(port)m_axi_in_array_BUSER");
    sc_trace(mVcdFile, in_array_offset, "(port)in_array_offset");
    sc_trace(mVcdFile, out_array, "(port)out_array");
    sc_trace(mVcdFile, out_array_out_din, "(port)out_array_out_din");
    sc_trace(mVcdFile, out_array_out_full_n, "(port)out_array_out_full_n");
    sc_trace(mVcdFile, out_array_out_write, "(port)out_array_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, in_stream_V_blk_n, "in_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_i_i_reg_183, "exitcond_i_i_reg_183");
    sc_trace(mVcdFile, ap_reg_pp0_iter1_exitcond_i_i_reg_183, "ap_reg_pp0_iter1_exitcond_i_i_reg_183");
    sc_trace(mVcdFile, in_array_blk_n_AR, "in_array_blk_n_AR");
    sc_trace(mVcdFile, in_array_blk_n_R, "in_array_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, out_array_out_blk_n, "out_array_out_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_i_i_reg_133, "i_i_i_reg_133");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_in_array_ARREADY, "ap_sig_ioackin_m_axi_in_array_ARREADY");
    sc_trace(mVcdFile, exitcond_i_i_fu_165_p2, "exitcond_i_i_fu_165_p2");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter0, "ap_block_state8_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter1, "ap_block_state9_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter2, "ap_block_state10_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_171_p2, "i_fu_171_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, temp_reg_192, "temp_reg_192");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state8, "ap_condition_pp0_exit_iter0_state8");
    sc_trace(mVcdFile, sext_i_i_fu_154_p1, "sext_i_i_fu_154_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_in_array_ARREADY, "ap_reg_ioackin_m_axi_in_array_ARREADY");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, in_array_offset1_i_i_fu_144_p4, "in_array_offset1_i_i_fu_144_p4");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_298, "ap_condition_298");
    sc_trace(mVcdFile, ap_condition_153, "ap_condition_153");
#endif

    }
}

write_pixels_to_stre::~write_pixels_to_stre() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void write_pixels_to_stre::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state8.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                    esl_seteq<1,1,1>(out_array_out_full_n.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state8.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state8.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                    esl_seteq<1,1,1>(out_array_out_full_n.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_in_array_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
            if (esl_seteq<1,1,1>(ap_condition_153.read(), ap_const_boolean_1)) {
                ap_reg_ioackin_m_axi_in_array_ARREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_condition_298.read(), ap_const_boolean_1)) {
                ap_reg_ioackin_m_axi_in_array_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_fu_165_p2.read()))) {
        i_i_i_reg_133 = i_fu_171_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(out_array_out_full_n.read(), ap_const_logic_1))) {
        i_i_i_reg_133 = ap_const_lv19_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_reg_pp0_iter1_exitcond_i_i_reg_183 = exitcond_i_i_reg_183.read();
        exitcond_i_i_reg_183 = exitcond_i_i_fu_165_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_183.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        temp_reg_192 = m_axi_in_array_RDATA.read();
    }
}

void write_pixels_to_stre::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[7];
}

void write_pixels_to_stre::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void write_pixels_to_stre::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[8];
}

void write_pixels_to_stre::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void write_pixels_to_stre::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void write_pixels_to_stre::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_183.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_array_RVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_i_reg_183.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_full_n.read())));
}

void write_pixels_to_stre::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_183.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_array_RVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_i_reg_183.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_full_n.read())));
}

void write_pixels_to_stre::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_183.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_array_RVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_i_reg_183.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_full_n.read())));
}

void write_pixels_to_stre::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void write_pixels_to_stre::thread_ap_block_state10_pp0_stage0_iter2() {
    ap_block_state10_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_i_reg_183.read()) && esl_seteq<1,1,1>(ap_const_logic_0, in_stream_V_full_n.read()));
}

void write_pixels_to_stre::thread_ap_block_state8_pp0_stage0_iter0() {
    ap_block_state8_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void write_pixels_to_stre::thread_ap_block_state9_pp0_stage0_iter1() {
    ap_block_state9_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_183.read()) && esl_seteq<1,1,1>(ap_const_logic_0, m_axi_in_array_RVALID.read()));
}

void write_pixels_to_stre::thread_ap_condition_153() {
    ap_condition_153 = !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_in_array_ARREADY.read()));
}

void write_pixels_to_stre::thread_ap_condition_298() {
    ap_condition_298 = (!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, m_axi_in_array_ARREADY.read()));
}

void write_pixels_to_stre::thread_ap_condition_pp0_exit_iter0_state8() {
    if (esl_seteq<1,1,1>(exitcond_i_i_fu_165_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state8 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state8 = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void write_pixels_to_stre::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void write_pixels_to_stre::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void write_pixels_to_stre::thread_ap_sig_ioackin_m_axi_in_array_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_in_array_ARREADY.read())) {
        ap_sig_ioackin_m_axi_in_array_ARREADY = m_axi_in_array_ARREADY.read();
    } else {
        ap_sig_ioackin_m_axi_in_array_ARREADY = ap_const_logic_1;
    }
}

void write_pixels_to_stre::thread_exitcond_i_i_fu_165_p2() {
    exitcond_i_i_fu_165_p2 = (!i_i_i_reg_133.read().is_01() || !ap_const_lv19_57E40.is_01())? sc_lv<1>(): sc_lv<1>(i_i_i_reg_133.read() == ap_const_lv19_57E40);
}

void write_pixels_to_stre::thread_i_fu_171_p2() {
    i_fu_171_p2 = (!i_i_i_reg_133.read().is_01() || !ap_const_lv19_1.is_01())? sc_lv<19>(): (sc_biguint<19>(i_i_i_reg_133.read()) + sc_biguint<19>(ap_const_lv19_1));
}

void write_pixels_to_stre::thread_in_array_blk_n_AR() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        in_array_blk_n_AR = m_axi_in_array_ARREADY.read();
    } else {
        in_array_blk_n_AR = ap_const_logic_1;
    }
}

void write_pixels_to_stre::thread_in_array_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_183.read()))) {
        in_array_blk_n_R = m_axi_in_array_RVALID.read();
    } else {
        in_array_blk_n_R = ap_const_logic_1;
    }
}

void write_pixels_to_stre::thread_in_array_offset1_i_i_fu_144_p4() {
    in_array_offset1_i_i_fu_144_p4 = in_array_offset.read().range(31, 2);
}

void write_pixels_to_stre::thread_in_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_i_reg_183.read()))) {
        in_stream_V_blk_n = in_stream_V_full_n.read();
    } else {
        in_stream_V_blk_n = ap_const_logic_1;
    }
}

void write_pixels_to_stre::thread_in_stream_V_din() {
    in_stream_V_din = temp_reg_192.read();
}

void write_pixels_to_stre::thread_in_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_pp0_iter1_exitcond_i_i_reg_183.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_stream_V_write = ap_const_logic_1;
    } else {
        in_stream_V_write = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_internal_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_m_axi_in_array_ARADDR() {
    m_axi_in_array_ARADDR =  (sc_lv<32>) (sext_i_i_fu_154_p1.read());
}

void write_pixels_to_stre::thread_m_axi_in_array_ARBURST() {
    m_axi_in_array_ARBURST = ap_const_lv2_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARCACHE() {
    m_axi_in_array_ARCACHE = ap_const_lv4_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARID() {
    m_axi_in_array_ARID = ap_const_lv1_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARLEN() {
    m_axi_in_array_ARLEN = ap_const_lv32_57E40;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARLOCK() {
    m_axi_in_array_ARLOCK = ap_const_lv2_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARPROT() {
    m_axi_in_array_ARPROT = ap_const_lv3_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARQOS() {
    m_axi_in_array_ARQOS = ap_const_lv4_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARREGION() {
    m_axi_in_array_ARREGION = ap_const_lv4_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARSIZE() {
    m_axi_in_array_ARSIZE = ap_const_lv3_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARUSER() {
    m_axi_in_array_ARUSER = ap_const_lv1_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_in_array_ARREADY.read()))) {
        m_axi_in_array_ARVALID = ap_const_logic_1;
    } else {
        m_axi_in_array_ARVALID = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_m_axi_in_array_AWADDR() {
    m_axi_in_array_AWADDR = ap_const_lv32_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWBURST() {
    m_axi_in_array_AWBURST = ap_const_lv2_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWCACHE() {
    m_axi_in_array_AWCACHE = ap_const_lv4_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWID() {
    m_axi_in_array_AWID = ap_const_lv1_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWLEN() {
    m_axi_in_array_AWLEN = ap_const_lv32_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWLOCK() {
    m_axi_in_array_AWLOCK = ap_const_lv2_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWPROT() {
    m_axi_in_array_AWPROT = ap_const_lv3_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWQOS() {
    m_axi_in_array_AWQOS = ap_const_lv4_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWREGION() {
    m_axi_in_array_AWREGION = ap_const_lv4_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWSIZE() {
    m_axi_in_array_AWSIZE = ap_const_lv3_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWUSER() {
    m_axi_in_array_AWUSER = ap_const_lv1_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_AWVALID() {
    m_axi_in_array_AWVALID = ap_const_logic_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_BREADY() {
    m_axi_in_array_BREADY = ap_const_logic_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_i_reg_183.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        m_axi_in_array_RREADY = ap_const_logic_1;
    } else {
        m_axi_in_array_RREADY = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_m_axi_in_array_WDATA() {
    m_axi_in_array_WDATA = ap_const_lv32_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_WID() {
    m_axi_in_array_WID = ap_const_lv1_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_WLAST() {
    m_axi_in_array_WLAST = ap_const_logic_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_WSTRB() {
    m_axi_in_array_WSTRB = ap_const_lv4_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_WUSER() {
    m_axi_in_array_WUSER = ap_const_lv1_0;
}

void write_pixels_to_stre::thread_m_axi_in_array_WVALID() {
    m_axi_in_array_WVALID = ap_const_logic_0;
}

void write_pixels_to_stre::thread_out_array_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        out_array_out_blk_n = out_array_out_full_n.read();
    } else {
        out_array_out_blk_n = ap_const_logic_1;
    }
}

void write_pixels_to_stre::thread_out_array_out_din() {
    out_array_out_din = out_array.read();
}

void write_pixels_to_stre::thread_out_array_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(out_array_out_full_n.read(), ap_const_logic_1))) {
        out_array_out_write = ap_const_logic_1;
    } else {
        out_array_out_write = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void write_pixels_to_stre::thread_sext_i_i_fu_154_p1() {
    sext_i_i_fu_154_p1 = esl_zext<64,30>(in_array_offset1_i_i_fu_144_p4.read());
}

void write_pixels_to_stre::thread_start_out() {
    start_out = real_start.read();
}

void write_pixels_to_stre::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void write_pixels_to_stre::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_m_axi_in_array_ARREADY.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(out_array_out_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_i_i_fu_165_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(exitcond_i_i_fu_165_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXX";
            break;
    }
}

}

