// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XFILTER_WRAPPER_H
#define XFILTER_WRAPPER_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xfilter_wrapper_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XFilter_wrapper_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XFilter_wrapper;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XFilter_wrapper_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XFilter_wrapper_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XFilter_wrapper_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XFilter_wrapper_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XFilter_wrapper_Initialize(XFilter_wrapper *InstancePtr, u16 DeviceId);
XFilter_wrapper_Config* XFilter_wrapper_LookupConfig(u16 DeviceId);
int XFilter_wrapper_CfgInitialize(XFilter_wrapper *InstancePtr, XFilter_wrapper_Config *ConfigPtr);
#else
int XFilter_wrapper_Initialize(XFilter_wrapper *InstancePtr, const char* InstanceName);
int XFilter_wrapper_Release(XFilter_wrapper *InstancePtr);
#endif

void XFilter_wrapper_Start(XFilter_wrapper *InstancePtr);
u32 XFilter_wrapper_IsDone(XFilter_wrapper *InstancePtr);
u32 XFilter_wrapper_IsIdle(XFilter_wrapper *InstancePtr);
u32 XFilter_wrapper_IsReady(XFilter_wrapper *InstancePtr);
void XFilter_wrapper_EnableAutoRestart(XFilter_wrapper *InstancePtr);
void XFilter_wrapper_DisableAutoRestart(XFilter_wrapper *InstancePtr);

void XFilter_wrapper_Set_in_array(XFilter_wrapper *InstancePtr, u32 Data);
u32 XFilter_wrapper_Get_in_array(XFilter_wrapper *InstancePtr);
void XFilter_wrapper_Set_out_array(XFilter_wrapper *InstancePtr, u32 Data);
u32 XFilter_wrapper_Get_out_array(XFilter_wrapper *InstancePtr);

void XFilter_wrapper_InterruptGlobalEnable(XFilter_wrapper *InstancePtr);
void XFilter_wrapper_InterruptGlobalDisable(XFilter_wrapper *InstancePtr);
void XFilter_wrapper_InterruptEnable(XFilter_wrapper *InstancePtr, u32 Mask);
void XFilter_wrapper_InterruptDisable(XFilter_wrapper *InstancePtr, u32 Mask);
void XFilter_wrapper_InterruptClear(XFilter_wrapper *InstancePtr, u32 Mask);
u32 XFilter_wrapper_InterruptGetEnabled(XFilter_wrapper *InstancePtr);
u32 XFilter_wrapper_InterruptGetStatus(XFilter_wrapper *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
