-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity write_pixels_to_stre is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    in_stream_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_stream_V_full_n : IN STD_LOGIC;
    in_stream_V_write : OUT STD_LOGIC;
    m_axi_in_array_AWVALID : OUT STD_LOGIC;
    m_axi_in_array_AWREADY : IN STD_LOGIC;
    m_axi_in_array_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_array_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_array_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_array_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_array_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_array_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_array_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_array_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_array_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_array_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_WVALID : OUT STD_LOGIC;
    m_axi_in_array_WREADY : IN STD_LOGIC;
    m_axi_in_array_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_array_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_array_WLAST : OUT STD_LOGIC;
    m_axi_in_array_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_ARVALID : OUT STD_LOGIC;
    m_axi_in_array_ARREADY : IN STD_LOGIC;
    m_axi_in_array_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_array_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_array_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_array_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_array_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_array_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_array_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_array_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_array_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_array_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_RVALID : IN STD_LOGIC;
    m_axi_in_array_RREADY : OUT STD_LOGIC;
    m_axi_in_array_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_array_RLAST : IN STD_LOGIC;
    m_axi_in_array_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_array_BVALID : IN STD_LOGIC;
    m_axi_in_array_BREADY : OUT STD_LOGIC;
    m_axi_in_array_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_array_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_array_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_array_offset : IN STD_LOGIC_VECTOR (31 downto 0);
    out_array : IN STD_LOGIC_VECTOR (31 downto 0);
    out_array_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_array_out_full_n : IN STD_LOGIC;
    out_array_out_write : OUT STD_LOGIC );
end;


architecture behav of write_pixels_to_stre is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv32_57E40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000001010111111001000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv19_57E40 : STD_LOGIC_VECTOR (18 downto 0) := "1010111111001000000";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal in_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond_i_i_reg_183 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter1_exitcond_i_i_reg_183 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_array_blk_n_AR : STD_LOGIC;
    signal in_array_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal out_array_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal i_i_i_reg_133 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_sig_ioackin_m_axi_in_array_ARREADY : STD_LOGIC;
    signal exitcond_i_i_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_171_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal temp_reg_192 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state8 : STD_LOGIC;
    signal sext_i_i_fu_154_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_m_axi_in_array_ARREADY : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal in_array_offset1_i_i_fu_144_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_298 : BOOLEAN;
    signal ap_condition_153 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (out_array_out_full_n = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state8)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state8);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (out_array_out_full_n = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_in_array_ARREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_in_array_ARREADY <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    if ((ap_const_boolean_1 = ap_condition_153)) then 
                        ap_reg_ioackin_m_axi_in_array_ARREADY <= ap_const_logic_0;
                    elsif ((ap_const_boolean_1 = ap_condition_298)) then 
                        ap_reg_ioackin_m_axi_in_array_ARREADY <= ap_const_logic_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_i_i_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_fu_165_p2 = ap_const_lv1_0))) then 
                i_i_i_reg_133 <= i_fu_171_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state7) and (out_array_out_full_n = ap_const_logic_1))) then 
                i_i_i_reg_133 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_reg_pp0_iter1_exitcond_i_i_reg_183 <= exitcond_i_i_reg_183;
                exitcond_i_i_reg_183 <= exitcond_i_i_fu_165_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_183 = ap_const_lv1_0))) then
                temp_reg_192 <= m_axi_in_array_RDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, out_array_out_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1, ap_CS_fsm_state7, ap_sig_ioackin_m_axi_in_array_ARREADY, exitcond_i_i_fu_165_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_sig_ioackin_m_axi_in_array_ARREADY = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (out_array_out_full_n = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond_i_i_fu_165_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond_i_i_fu_165_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(8);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_stream_V_full_n, m_axi_in_array_RVALID, ap_enable_reg_pp0_iter2, exitcond_i_i_reg_183, ap_reg_pp0_iter1_exitcond_i_i_reg_183, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= (((m_axi_in_array_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_i_i_reg_183 = ap_const_lv1_0)) or ((in_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_reg_pp0_iter1_exitcond_i_i_reg_183 = ap_const_lv1_0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_stream_V_full_n, m_axi_in_array_RVALID, ap_enable_reg_pp0_iter2, exitcond_i_i_reg_183, ap_reg_pp0_iter1_exitcond_i_i_reg_183, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_in_array_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_i_i_reg_183 = ap_const_lv1_0)) or ((in_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_reg_pp0_iter1_exitcond_i_i_reg_183 = ap_const_lv1_0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_stream_V_full_n, m_axi_in_array_RVALID, ap_enable_reg_pp0_iter2, exitcond_i_i_reg_183, ap_reg_pp0_iter1_exitcond_i_i_reg_183, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_in_array_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_i_i_reg_183 = ap_const_lv1_0)) or ((in_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_reg_pp0_iter1_exitcond_i_i_reg_183 = ap_const_lv1_0)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state10_pp0_stage0_iter2_assign_proc : process(in_stream_V_full_n, ap_reg_pp0_iter1_exitcond_i_i_reg_183)
    begin
                ap_block_state10_pp0_stage0_iter2 <= ((in_stream_V_full_n = ap_const_logic_0) and (ap_reg_pp0_iter1_exitcond_i_i_reg_183 = ap_const_lv1_0));
    end process;

        ap_block_state8_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter1_assign_proc : process(m_axi_in_array_RVALID, exitcond_i_i_reg_183)
    begin
                ap_block_state9_pp0_stage0_iter1 <= ((m_axi_in_array_RVALID = ap_const_logic_0) and (exitcond_i_i_reg_183 = ap_const_lv1_0));
    end process;


    ap_condition_153_assign_proc : process(real_start, ap_done_reg, ap_sig_ioackin_m_axi_in_array_ARREADY)
    begin
                ap_condition_153 <= not(((ap_sig_ioackin_m_axi_in_array_ARREADY = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1)));
    end process;


    ap_condition_298_assign_proc : process(real_start, ap_done_reg, m_axi_in_array_ARREADY)
    begin
                ap_condition_298 <= (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (m_axi_in_array_ARREADY = ap_const_logic_1));
    end process;


    ap_condition_pp0_exit_iter0_state8_assign_proc : process(exitcond_i_i_fu_165_p2)
    begin
        if ((exitcond_i_i_fu_165_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state8 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    ap_sig_ioackin_m_axi_in_array_ARREADY_assign_proc : process(m_axi_in_array_ARREADY, ap_reg_ioackin_m_axi_in_array_ARREADY)
    begin
        if ((ap_reg_ioackin_m_axi_in_array_ARREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_in_array_ARREADY <= m_axi_in_array_ARREADY;
        else 
            ap_sig_ioackin_m_axi_in_array_ARREADY <= ap_const_logic_1;
        end if; 
    end process;

    exitcond_i_i_fu_165_p2 <= "1" when (i_i_i_reg_133 = ap_const_lv19_57E40) else "0";
    i_fu_171_p2 <= std_logic_vector(unsigned(i_i_i_reg_133) + unsigned(ap_const_lv19_1));

    in_array_blk_n_AR_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, m_axi_in_array_ARREADY)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_array_blk_n_AR <= m_axi_in_array_ARREADY;
        else 
            in_array_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    in_array_blk_n_R_assign_proc : process(m_axi_in_array_RVALID, ap_block_pp0_stage0, exitcond_i_i_reg_183, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond_i_i_reg_183 = ap_const_lv1_0))) then 
            in_array_blk_n_R <= m_axi_in_array_RVALID;
        else 
            in_array_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    in_array_offset1_i_i_fu_144_p4 <= in_array_offset(31 downto 2);

    in_stream_V_blk_n_assign_proc : process(in_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, ap_reg_pp0_iter1_exitcond_i_i_reg_183)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_reg_pp0_iter1_exitcond_i_i_reg_183 = ap_const_lv1_0))) then 
            in_stream_V_blk_n <= in_stream_V_full_n;
        else 
            in_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_V_din <= temp_reg_192;

    in_stream_V_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond_i_i_reg_183, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_reg_pp0_iter1_exitcond_i_i_reg_183 = ap_const_lv1_0))) then 
            in_stream_V_write <= ap_const_logic_1;
        else 
            in_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_array_ARADDR <= sext_i_i_fu_154_p1(32 - 1 downto 0);
    m_axi_in_array_ARBURST <= ap_const_lv2_0;
    m_axi_in_array_ARCACHE <= ap_const_lv4_0;
    m_axi_in_array_ARID <= ap_const_lv1_0;
    m_axi_in_array_ARLEN <= ap_const_lv32_57E40;
    m_axi_in_array_ARLOCK <= ap_const_lv2_0;
    m_axi_in_array_ARPROT <= ap_const_lv3_0;
    m_axi_in_array_ARQOS <= ap_const_lv4_0;
    m_axi_in_array_ARREGION <= ap_const_lv4_0;
    m_axi_in_array_ARSIZE <= ap_const_lv3_0;
    m_axi_in_array_ARUSER <= ap_const_lv1_0;

    m_axi_in_array_ARVALID_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ap_reg_ioackin_m_axi_in_array_ARREADY)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_reg_ioackin_m_axi_in_array_ARREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_in_array_ARVALID <= ap_const_logic_1;
        else 
            m_axi_in_array_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_array_AWADDR <= ap_const_lv32_0;
    m_axi_in_array_AWBURST <= ap_const_lv2_0;
    m_axi_in_array_AWCACHE <= ap_const_lv4_0;
    m_axi_in_array_AWID <= ap_const_lv1_0;
    m_axi_in_array_AWLEN <= ap_const_lv32_0;
    m_axi_in_array_AWLOCK <= ap_const_lv2_0;
    m_axi_in_array_AWPROT <= ap_const_lv3_0;
    m_axi_in_array_AWQOS <= ap_const_lv4_0;
    m_axi_in_array_AWREGION <= ap_const_lv4_0;
    m_axi_in_array_AWSIZE <= ap_const_lv3_0;
    m_axi_in_array_AWUSER <= ap_const_lv1_0;
    m_axi_in_array_AWVALID <= ap_const_logic_0;
    m_axi_in_array_BREADY <= ap_const_logic_0;

    m_axi_in_array_RREADY_assign_proc : process(exitcond_i_i_reg_183, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_reg_183 = ap_const_lv1_0))) then 
            m_axi_in_array_RREADY <= ap_const_logic_1;
        else 
            m_axi_in_array_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_array_WDATA <= ap_const_lv32_0;
    m_axi_in_array_WID <= ap_const_lv1_0;
    m_axi_in_array_WLAST <= ap_const_logic_0;
    m_axi_in_array_WSTRB <= ap_const_lv4_0;
    m_axi_in_array_WUSER <= ap_const_lv1_0;
    m_axi_in_array_WVALID <= ap_const_logic_0;

    out_array_out_blk_n_assign_proc : process(out_array_out_full_n, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            out_array_out_blk_n <= out_array_out_full_n;
        else 
            out_array_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_array_out_din <= out_array;

    out_array_out_write_assign_proc : process(out_array_out_full_n, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (out_array_out_full_n = ap_const_logic_1))) then 
            out_array_out_write <= ap_const_logic_1;
        else 
            out_array_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    sext_i_i_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_array_offset1_i_i_fu_144_p4),64));
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
